### ISSUE TITLE
Multiple TRVs support/formatting? 

### ISSUE THREAD

**Issue by angrysmiley** [ColinRobbins/Homeassistant-Lightwave-TRV#2]
Does the proxy support multiple TRVs?  

If so,  how is the proper way of formatting the entries. 

As It seems it only displays the top entry no matter which one is on top...

**Comment by ColinRobbins** [comment]
Yes, I have 10 TRVs.
Sounds like a problem with the HA configuration in the configuration.yaml` file.
Most probably the indentation.

**Comment by angrysmiley** [comment]
That was indeed my first thought. 

But after doing some manual tests with Netcat,  I noticed it was responding with 123,OK to every query! 
Thus, I decided to try to reset the LightwaveRF device,  which seems to have solved the issue so far.
