### ISSUE TITLE
new install

### ISSUE THREAD

**Issue by ste19m** [ColinRobbins/Homeassistant-Lightwave-TRV#3]
Hi Colin, im new to home assistant and im really wanting to integrate my trvs into lightwave. im struggling to understand exactly how to install your work around can you help? maybe a "how to install for dummies" way?

**Comment by ColinRobbins** [comment]
Are you using the HA operating system, or did you use one of the other installation methods?
If HA operating system, do you have another computer running Linux?

**Comment by ste19m** [comment]
Hi, thanks for the prompt reply. I’m currently operating on a raspberry pi 4 using the ha operating system and don’t have any other computer running Linux 

Kind Regards,
Steve Challinor

**Comment by ColinRobbins** [comment]
I use HA core, not the HA Operating System so have full access to the Linux machine.
With HA OS as far as I am aware access to the Linux system is limited, so installing this proxy is difficult (not certain it is possible - someone did try).
So I think you’ll need a different Linux machine to install the proxy on.
Not ideal, but all I can suggest, unless you are able to dabble with the HA OS.

**Comment by ste19m** [comment]
Looking in my system health it says I’m on core 2022 5.3 with home assistant os running Linux operating system that still mean I’m screwed?

Kind Regards,
Steve Challinor

**Comment by ColinRobbins** [comment]
Sorry, I don’t know enough about the HA OS, as I don’t use it.
Are you able to log into the Linux machine and run the command `pip3 install lw-trv-proxy`

**Comment by ste19m** [comment]
No it would have to be on a virtual machine to be able to do it. I don’t know if this makes a difference or not but the trvs I’m trying to integrate are actually Honeywell hr92s which run into my Lightwave link plus hub would I be able to integrate any easier or is this an unknown?

Kind Regards,
Steve Challinor

**Comment by ColinRobbins** [comment]
Sorry, not really sure about that.
All depends on how the Honeywell TRVs communicate with Lightwave Hub. If they use UDP broadcast, like the Lightwave TRVs it may work.

If you have a Lightwave hub version 2, then this integration may be better: https://github.com/bigbadblunt/homeassistant-lightwave2

**Comment by ste19m** [comment]
They apparently do use udp broadcast which is why they integrate with Lightwave. Do you know if the integration you have just shown me includes trvs as there is no mention of them at all? Sorry to quiz you so much

Kind Regards,
Steve Challinor

**Comment by ColinRobbins** [comment]
Sorry, don’t know,  I have a v1 hub.

**Comment by ste19m** [comment]
Thanks for the advice I’ve just added the integration and everything  has gone in and worked instantly including the trvs

Kind Regards,
Steve Challinor
